#!/bin/bash

# Deploy CSS
aws s3 cp --recursive ./resources/caheriaguilar.com/css s3://caheriaguilar.com/static/css

# Deploy images
aws s3 cp --recursive ./resources/caheriaguilar.com/images/nav-bar s3://caheriaguilar.com/static/images/nav-bar

aws s3 cp ./resources/andrewslai.com/static/images/images.svg     s3://caheriaguilar.com/static/images/images.svg
aws s3 cp ./resources/andrewslai.com/static/images/writing.svg    s3://caheriaguilar.com/static/images/writing.svg
aws s3 cp ./resources/andrewslai.com/static/images/audiences.svg  s3://caheriaguilar.com/static/images/audiences.svg

#aws s3 cp --recursive ./resources/public/corporis-fabrica   s3://caheriaguilar.com/static/corporis-fabrica/
aws s3 cp ./resources/caheriaguilar.com/index.html              s3://caheriaguilar.com/static/index.html
# Background #0e766d
# Light      #aeadff00
