#!/bin/bash

# Deploy CSS
aws s3 cp --recursive ./resources/public-sahil/css s3://sahiltalkingcents/static/css

# Deploy images
aws s3 cp --recursive ./resources/public-sahil/images/nav-bar s3://sahiltalkingcents/static/images/nav-bar

aws s3 cp ./resources/public-sahil/images/images.svg     s3://sahiltalkingcents/static/images/images.svg
aws s3 cp ./resources/public-sahil/images/writing.svg    s3://sahiltalkingcents/static/images/writing.svg
aws s3 cp ./resources/public-sahil/images/audiences.svg  s3://sahiltalkingcents/static/images/audiences.svg

#aws s3 cp --recursive ./resources/public/corporis-fabrica   s3://sahiltalkingcents/static/corporis-fabrica/
aws s3 cp ./resources/public-sahil/index.html            s3://sahiltalkingcents/static/index.html

# Background #0e766d
# Light      #aeadff00
