#!/bin/bash

SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)

pushd "$SCRIPT_DIR/../../"

echo "Deploying frontend to kaleidoscope bucket..."

aws s3 sync resources/andrewslai.com/static s3://andrewslai.com/static \
    --exclude "*/cljs-runtime/*" \
    --exclude "*/shareable_stories/*" # --dryrun

popd
