#!/bin/bash

SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)

pushd "$SCRIPT_DIR/../../"

echo "Incrementing package version..."
npm version patch

echo "Deploying frontend to kaleidoscope bucket..."
aws s3 sync dist/assets s3://kaleidoscope.client/assets

popd
