#!/bin/bash

aws s3 cp ./resources/public/js/compiled/andrewslai/andrewslai.js s3://andrewslai/js/compiled/andrewslai.js
aws s3 cp ./resources/public/js/compiled/andrewslai/andrewslai.js.map s3://andrewslai/js/compiled/andrewslai.js.map
aws s3 cp ./resources/public/js/compiled/andrewslai/editor.js s3://andrewslai/js/compiled/andrewslai/editor.js
aws s3 cp ./resources/public/js/compiled/andrewslai/editor.js.map s3://andrewslai/js/compiled/andrewslai/editor.js.map
aws s3 cp ./resources/public/js/compiled/andrewslai/manifest.edn s3://andrewslai/js/compiled/manifest.edn
aws s3 cp ./resources/public/js/compiled/andrewslai/module-loader.edn s3://andrewslai/js/compiled/module-loader.edn
aws s3 cp ./resources/public/js/compiled/andrewslai/module-loader.json s3://andrewslai/js/compiled/module-loader.json
echo "Incrementing package version..."
npm version patch
