#!/bin/bash

SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)

pushd "$SCRIPT_DIR/../../"

echo "Incrementing package version..."
npm version patch

echo "Deploying frontend to kaleidoscope bucket..."
aws s3 sync resources/kaleidoscope.client/static s3://kaleidoscope.client/static \
    --exclude "*/cljs-runtime/*" \
    --exclude "*/shareable_stories/*" # --dryrun

popd
