#!/bin/bash

SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)

pushd "$SCRIPT_DIR/../../"

echo "Incrementing package version..."
npm version patch

echo "Deploying frontend to kaleidoscope bucket..."
aws s3 sync resources/kaleidoscope.client/static/dist/assets s3://kaleidoscope.client/assets --delete
aws s3 cp resources/kaleidoscope.client/static/dist/index.html s3://kaleidoscope.client/index.html

popd
